-- ============================================================================
-- Registru Digital Bibliotecă — schema Supabase (PostgreSQL)
-- ----------------------------------------------------------------------------
-- Portare 1:1 a modelelor SQLAlchemy (app/database/models.py) în Postgres.
-- Rulați acest fișier în Supabase → SQL Editor (o singură dată la configurare).
--
-- Multi-user: RLS este activat pe fiecare tabel; orice utilizator AUTENTIFICAT
-- (login Supabase) poate citi și scrie. O singură bibliotecă / registru comun.
-- Pentru mai multe biblioteci separate, adăugați o coloană library_id + politici.
-- ============================================================================

-- Trigger comun pentru updated_at ------------------------------------------------
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ----------------------------------------------------------------------------
-- Tabele suport globale
-- ----------------------------------------------------------------------------
create table if not exists personal (
  id            bigint generated by default as identity primary key,
  nume_prenume  text not null unique,
  activ         boolean not null default true
);

create table if not exists range_config (
  id          bigint generated by default as identity primary key,
  parte       text not null,
  coloana     text not null,
  valoare_min integer not null default 0,
  valoare_max integer not null default 20,
  constraint uq_range_parte_coloana unique (parte, coloana)
);

create table if not exists etichete_custom (
  id                bigint generated by default as identity primary key,
  parte             text not null,
  camp              text not null,
  eticheta_default  text not null,
  eticheta_custom   text,
  constraint uq_eticheta_parte_camp unique (parte, camp)
);

create table if not exists app_settings (
  cheie   text primary key,
  valoare text
);

create table if not exists text_presets (
  id      bigint generated by default as identity primary key,
  parte   text not null,
  camp    text not null,
  valoare text not null,
  constraint uq_text_preset_parte_camp_val unique (parte, camp, valoare)
);

-- ----------------------------------------------------------------------------
-- PARTEA I — Evidența utilizatorilor (Copii + Adulți împreună)
-- ----------------------------------------------------------------------------
create table if not exists evidenta_utilizatori (
  id                bigint generated by default as identity primary key,
  an                integer not null,
  luna              integer not null,
  data              text not null,
  adulti            integer not null default 0,
  copii_pana_16     integer not null default 0,
  prescolari        integer not null default 0,
  elevi             integer not null default 0,
  studenti          integer not null default 0,
  intelectuali      integer not null default 0,
  muncitori         integer not null default 0,
  pensionari        integer not null default 0,
  someri            integer not null default 0,
  alte_categorii    integer not null default 0,
  tineri_17_34      integer not null default 0,
  adulti_35_64      integer not null default 0,
  varstnici_65_plus integer not null default 0,
  sex_copii_f       integer not null default 0,
  sex_copii_m       integer not null default 0,
  sex_adulti_f      integer not null default 0,
  sex_adulti_m      integer not null default 0,
  is_auto_generated boolean not null default false,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint uq_part01_an_luna_data unique (an, luna, data)
);

-- ----------------------------------------------------------------------------
-- PARTEA II — Evidența utilizatorilor (Copii / Adulți separat)
-- ----------------------------------------------------------------------------
create table if not exists evidenta_utilizatori_copii_adulti (
  id                                bigint generated by default as identity primary key,
  an                                integer not null,
  luna                              integer not null,
  data                              text not null,
  categorie_varsta                  text not null,  -- 'copii' | 'adulti'
  intrari_total_zi                  integer not null default 0,
  imprumut_carti                    integer not null default 0,
  sedinte_calculatoare              integer not null default 0,
  activitati_culturale_stiintifice  integer not null default 0,
  instruiri                         integer not null default 0,
  alte_scopuri_excursii             integer not null default 0,
  vizite_virtuale_total             integer not null default 0,
  vizite_virtuale_pagina_web        integer not null default 0,
  vizite_virtuale_blog              integer not null default 0,
  vizitatori_virtuali_total         integer not null default 0,
  vizitatori_virtuali_pagina_web    integer not null default 0,
  vizitatori_virtuali_blog          integer not null default 0,
  facebook_vizualizari              integer not null default 0,
  facebook_impact                   integer not null default 0,
  facebook_interactiuni             integer not null default 0,
  instagram_vizualizari             integer not null default 0,
  instagram_impact                  integer not null default 0,
  instagram_interactiuni            integer not null default 0,
  twitter_vizualizari               integer not null default 0,
  twitter_impact                    integer not null default 0,
  twitter_interactiuni              integer not null default 0,
  is_auto_generated                 boolean not null default false,
  created_at                        timestamptz not null default now(),
  updated_at                        timestamptz not null default now(),
  constraint uq_part02_an_luna_data_cat unique (an, luna, data, categorie_varsta)
);

-- ----------------------------------------------------------------------------
-- PARTEA III — Documente înregistrate (Copii / Adulți)
-- ----------------------------------------------------------------------------
create table if not exists documente_inregistrate (
  id                          bigint generated by default as identity primary key,
  an                          integer not null,
  luna                        integer not null,
  data                        text not null,
  categorie_varsta            text not null,
  total_imprumuturi           integer not null default 0,
  consultare_pe_loc           integer not null default 0,
  imprumut_pe_loc             integer not null default 0,
  imprumut_la_domiciliu       integer not null default 0,
  imprumut_inter_bibliotecar  integer not null default 0,
  carti                       integer not null default 0,
  publicatii_seriale          integer not null default 0,
  documente_muzica            integer not null default 0,
  documente_audiovizuale      integer not null default 0,
  documente_electronice_cd_dvd integer not null default 0,
  alte_documente              integer not null default 0,
  limba_romana                integer not null default 0,
  alte_limbi                  integer not null default 0,
  is_auto_generated           boolean not null default false,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now(),
  constraint uq_part03_an_luna_data_cat unique (an, luna, data, categorie_varsta)
);

-- ----------------------------------------------------------------------------
-- PARTEA IV — Documente după conținut CZU (Copii / Adulți)
-- ----------------------------------------------------------------------------
create table if not exists documente_continut_czu (
  id                    bigint generated by default as identity primary key,
  an                    integer not null,
  luna                  integer not null,
  data                  text not null,
  categorie_varsta      text not null,
  total_imprumuturi     integer not null default 0,
  czu_0_generalitati    integer not null default 0,
  czu_1_filozofie       integer not null default 0,
  czu_2_religie         integer not null default 0,
  czu_3_stiinte_sociale integer not null default 0,
  czu_5_matematica      integer not null default 0,
  czu_6_stiinte_aplicate integer not null default 0,
  czu_7_arte            integer not null default 0,
  czu_8_limbi           integer not null default 0,
  czu_9_geografie       integer not null default 0,
  is_auto_generated     boolean not null default false,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  constraint uq_part04_an_luna_data_cat unique (an, luna, data, categorie_varsta)
);

-- ----------------------------------------------------------------------------
-- PARTEA V — Cercetări bibliografice (rânduri pe cereri)
-- ----------------------------------------------------------------------------
create table if not exists cercetari_bibliografice (
  id                            bigint generated by default as identity primary key,
  an                            integer not null,
  luna                          integer not null,
  categorie_varsta              text not null,
  data_primirii_cererii         text not null,
  total_referinte               integer not null default 0,
  date_despre_solicitant        text,
  statut_socio_profesional      text,
  referinta                     text,
  cercetare_bibliografica       text,
  consultatie                   text,
  referinta_tematica            text,
  referinta_de_concretizare     text,
  referinta_de_adresa           text,
  referinta_factologie          text,
  limite_cronologice            text,
  surse_consultatie             integer not null default 0,
  numar_descrieri_bibliografice integer not null default 0,
  surse_recomandate             integer not null default 0,
  data_finalizarii_cererii      text,
  responsabil                   text,
  tema                          text,
  tip_referinta_bibliografica   text,
  tip_referinta_grup            text,
  is_auto_generated             boolean not null default false,
  created_at                    timestamptz not null default now(),
  updated_at                    timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- PARTEA VI — Activități de informare (evenimente)
-- ----------------------------------------------------------------------------
create table if not exists activitati_informare (
  id                        bigint generated by default as identity primary key,
  an                        integer not null,
  luna                      integer not null,
  categorie_varsta          text not null,
  data                      text not null,
  grup_tinta_subiect        text,
  activitate_individuala    text,
  activitate_grup           text,
  activitate_public_larg    text,
  numar_participanti        integer not null default 0,
  participanti_masculin     integer not null default 0,
  participanti_feminin      integer not null default 0,
  documente_consultate      integer not null default 0,
  responsabil               text,
  gen_activitate            text,
  is_auto_generated         boolean not null default false,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- PARTEA VII — Documente electronice online (pe luni)
-- ----------------------------------------------------------------------------
create table if not exists documente_electronice (
  id                          bigint generated by default as identity primary key,
  an                          integer not null,
  luna                        integer not null,  -- 1..12
  categorie_varsta            text not null,
  total_documente_electronice integer not null default 0,
  mediu_email                 integer not null default 0,
  mediu_skype_retele_sociale  integer not null default 0,
  carti                       integer not null default 0,
  publicatii_seriale          integer not null default 0,
  documente_muzica            integer not null default 0,
  documente_audiovizuale      integer not null default 0,
  documente_electronice_cd_dvd integer not null default 0,
  alte_documente              integer not null default 0,
  limba_romana                integer not null default 0,
  alte_limbi                  integer not null default 0,
  is_auto_generated           boolean not null default false,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now(),
  constraint uq_part07_an_luna_cat unique (an, luna, categorie_varsta)
);

-- ----------------------------------------------------------------------------
-- PARTEA IX — Instruiri (multiple rânduri / zi)
-- ----------------------------------------------------------------------------
create table if not exists instruiri (
  id                  bigint generated by default as identity primary key,
  an                  integer not null,
  luna                integer not null,
  categorie_varsta    text not null default 'copii',
  data                text not null,
  format_online       boolean not null default false,
  format_offline      boolean not null default false,
  forma_formala       boolean not null default false,
  ore_formala         integer not null default 0,
  forma_non_formala   boolean not null default false,
  ore_non_formala     integer not null default 0,
  forma_informala     boolean not null default false,
  ore_informala       integer not null default 0,
  tema_instruirii     text,
  formator            text,
  total_participanti  integer not null default 0,
  prescolari          integer not null default 0,
  elevi               integer not null default 0,
  studenti            integer not null default 0,
  intelectuali        integer not null default 0,
  pensionari          integer not null default 0,
  someri              integer not null default 0,
  muncitori           integer not null default 0,
  alte_categorii      integer not null default 0,
  tineri_17_34        integer not null default 0,
  adulti_35_64        integer not null default 0,
  varstnici_65_plus   integer not null default 0,
  participanti_feminin  integer not null default 0,
  participanti_masculin integer not null default 0,
  adulti              integer not null default 0,
  copii_pana_16       integer not null default 0,
  is_auto_generated   boolean not null default false,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- PARTEA XI — Activități culturale și științifice
-- ----------------------------------------------------------------------------
create table if not exists activitati_culturale (
  id                    bigint generated by default as identity primary key,
  an                    integer not null,
  luna                  integer not null,
  categorie_varsta      text not null,
  data                  text,
  total_activitati      integer not null default 0,
  din_care_expozitii    integer not null default 0,
  tipul_activitatii     text,
  denumirea_activitatii text,
  total_participanti    integer not null default 0,
  participanti_masculin integer not null default 0,
  participanti_feminin  integer not null default 0,
  is_auto_generated     boolean not null default false,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- PARTEA XII — Activități culturale ONLINE
-- ----------------------------------------------------------------------------
create table if not exists activitati_online (
  id                    bigint generated by default as identity primary key,
  an                    integer not null,
  luna                  integer not null,
  categorie_varsta      text not null,
  data                  text not null,
  denumirea_activitatii text,
  tipul_activitatii     text,
  platforma             text,
  vizualizari           integer not null default 0,
  impact                integer not null default 0,
  participanti_total    integer not null default 0,
  participanti_masculin integer not null default 0,
  participanti_feminin  integer not null default 0,
  participanti_adulti   integer not null default 0,
  participanti_copii    integer not null default 0,
  is_auto_generated     boolean not null default false,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- PARTEA XIII — Parteneri
-- ----------------------------------------------------------------------------
create table if not exists parteneri (
  id                    bigint generated by default as identity primary key,
  partener              text not null,
  scope_local           boolean not null default false,
  scope_national        boolean not null default false,
  scope_international    boolean not null default false,
  date_contact          text,
  tip_contract          text,
  data_semnarii         text,
  termen_realizare      text,
  modalitati_realizare  text,
  participanti_total    integer not null default 0,
  participanti_adulti   integer not null default 0,
  participanti_copii    integer not null default 0,
  impact                integer not null default 0,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- PARTEA XIV — Voluntariat
-- ----------------------------------------------------------------------------
create table if not exists voluntariat (
  id                    bigint generated by default as identity primary key,
  nume_prenume          text not null,
  nr_contract           text,
  data_inceperii        text,
  data_incheierii       text,
  numar_ore             integer not null default 0,
  activitati_realizate  text,
  coordonator           text,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- ============================================================================
-- Trigger updated_at pe toate tabelele cu coloana updated_at
-- ============================================================================
do $$
declare t text;
begin
  foreach t in array array[
    'evidenta_utilizatori','evidenta_utilizatori_copii_adulti','documente_inregistrate',
    'documente_continut_czu','cercetari_bibliografice','activitati_informare',
    'documente_electronice','instruiri','activitati_culturale','activitati_online',
    'parteneri','voluntariat'
  ]
  loop
    execute format('drop trigger if exists trg_%1$s_updated on %1$s;', t);
    execute format(
      'create trigger trg_%1$s_updated before update on %1$s
       for each row execute function set_updated_at();', t);
  end loop;
end $$;

-- ============================================================================
-- Row Level Security — orice utilizator autentificat are acces complet
-- ============================================================================
do $$
declare t text;
begin
  foreach t in array array[
    'personal','range_config','etichete_custom','app_settings','text_presets',
    'evidenta_utilizatori','evidenta_utilizatori_copii_adulti','documente_inregistrate',
    'documente_continut_czu','cercetari_bibliografice','activitati_informare',
    'documente_electronice','instruiri','activitati_culturale','activitati_online',
    'parteneri','voluntariat'
  ]
  loop
    execute format('alter table %I enable row level security;', t);
    execute format('drop policy if exists p_auth_all on %I;', t);
    execute format(
      'create policy p_auth_all on %I
         for all to authenticated using (true) with check (true);', t);
  end loop;
end $$;

-- ============================================================================
-- Realtime — publică toate tabelele pentru sincronizare live (multi-user)
-- Necesar ca modificările altor utilizatori să apară automat.
-- ============================================================================
do $$
declare t text;
begin
  foreach t in array array[
    'personal','range_config','etichete_custom','app_settings','text_presets',
    'evidenta_utilizatori','evidenta_utilizatori_copii_adulti','documente_inregistrate',
    'documente_continut_czu','cercetari_bibliografice','activitati_informare',
    'documente_electronice','instruiri','activitati_culturale','activitati_online',
    'parteneri','voluntariat'
  ]
  loop
    begin
      execute format('alter publication supabase_realtime add table %I;', t);
    exception when duplicate_object then null; when others then null;
    end;
  end loop;
end $$;

-- ============================================================================
-- Storage — bucket privat „backups" pentru copii de rezervă în cloud (off-device)
-- ============================================================================
insert into storage.buckets (id, name, public) values ('backups', 'backups', false)
  on conflict (id) do nothing;

do $$
begin
  begin create policy "backups_auth_read" on storage.objects for select to authenticated using (bucket_id = 'backups'); exception when duplicate_object then null; end;
  begin create policy "backups_auth_insert" on storage.objects for insert to authenticated with check (bucket_id = 'backups'); exception when duplicate_object then null; end;
  begin create policy "backups_auth_delete" on storage.objects for delete to authenticated using (bucket_id = 'backups'); exception when duplicate_object then null; end;
end $$;
